# ===================================================================
# Copyright 2022 ZhengPu Shi
#  This file is part of VFCS. It is distributed under the MIT
#  "expat license". You should have recieved a LICENSE file with it.
# ===================================================================

all :
	make -C Introduction
	make -C PropulsionSystem
	make -C CoordinateSystem

clean :
	make -C Introduction clean
	make -C PropulsionSystem clean
	make -C CoordinateSystem clean
